---
# This task checks for any images on the local registry
- import_tasks: check.yml

# Skip config if images found on local registry (override with 'undercloud_docker_images_sync_force: True')
- import_tasks: skip.yml
  when: 
    - undercloud_docker_images_sync_configured | default(False) | bool == True
    - undercloud_docker_images_sync_force | default(False) | bool == False

# Configure docker registry and output overcloud-images.yml file for deployment and local upstream images yaml used for sync
- import_tasks: configure.yml
  when: (undercloud_docker_images_sync_configured | default(False) | bool == False) or (docker_registry_setup_force | default(False) | bool == True)

# Download images from upstream registry and push them to local undercloud registry
- import_tasks: sync.yml
  when: undercloud_docker_images_sync_sync | default(True) | bool == True

# Check and display images found with verbosity: 1
- import_tasks: check.yml

# Display error if registry is not populated with container images 
- import_tasks: error.yml
  when: docker_catalog.json.repositories == [] | default(False)
...
